export default {
  login: 'biplabwagle',
  id: 15272496,
  node_id: 'MDQ6VXNlcjE1MjcyNDk2',
  avatar_url: 'https://avatars.githubusercontent.com/u/15272496?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/biplabwagle',
  html_url: 'https://github.com/biplabwagle',
  followers_url: 'https://api.github.com/users/biplabwagle/followers',
  following_url:
    'https://api.github.com/users/biplabwagle/following{/other_user}',
  gists_url: 'https://api.github.com/users/biplabwagle/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/biplabwagle/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/biplabwagle/subscriptions',
  organizations_url: 'https://api.github.com/users/biplabwagle/orgs',
  repos_url: 'https://api.github.com/users/biplabwagle/repos',
  events_url: 'https://api.github.com/users/biplabwagle/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/biplabwagle/received_events',
  type: 'User',
  site_admin: false,
  name: 'Biplab Wagle',
  company: null,
  blog: '',
  location: 'Irving, Tx',
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 9,
  public_gists: 0,
  followers: 0,
  following: 1,
  created_at: '2015-10-24T01:04:28Z',
  updated_at: '2022-08-02T22:05:13Z',
};
